version: '2'
services:
    web:
        build: ./
        image: changecom_image
        volumes:
            - ./www:/var/www
        networks:
            - changecom-network
        ports:
            - 80:80
            - 443:443
        environment:
            APP_ENV: ${APP_ENV}
            XDEBUG_HOST: ${XDEBUG_HOST}
            run_jobs : 'false'

    db:
        image: mysql:5.7
        volumes:
            - data:/var/lib/mysql
        networks:
            - changecom-network
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: change
            MYSQL_USER: change
            MYSQL_PASSWORD: change

networks:
    changecom-network:
        driver: bridge
volumes:
    data:
        driver: local